version: "3.8"

services:
  db:
    container_name: concertApi-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: asan
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: concert
      PG DATA: ./dataset:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
